In [1]:
import random
import timeit
import numpy as np
from random import randrange

## Numpy functions

In [2]:
def sum_procedure():
    a = np.arange(10_000)
    
    sum_a = 0
    for i in a:
        sum_a += i
        
    return sum_a

print('Finish running 100 iterations in ' + str(timeit.timeit(stmt = sum_procedure, number = 100)) + 's')

Finish running 100 iterations in 0.17973170000000005s


In [3]:
def sum_numpy():
    a = np.arange(10_000)
        
    return np.sum(a)

print('Finish running 100 iterations in ' + str(timeit.timeit(stmt = sum_numpy, number = 100)) + 's')

Finish running 100 iterations in 0.003311299999999573s


In [4]:
def sum_product_procedure():
    a = np.zeros(100_000) + randrange(10)
    b = np.zeros(100_000) + randrange(10)
    
    sum_product = 0
    for i in range(len(a)):
        sum_product += a[i] * b[i]
        
    return sum_product

print('Finish running 100 iterations in ' + str(timeit.timeit(stmt = sum_product_procedure, number = 100)) + 's')

Finish running 100 iterations in 4.4603885000000005s


In [5]:
def sum_product_numpy():
    a = np.zeros(100_000) + randrange(10)
    b = np.zeros(100_000) + randrange(10)
        
    return np.dot(a, b)

print('Finish running 100 iterations in ' + str(timeit.timeit(stmt = sum_product_numpy, number = 100)) + 's')

Finish running 100 iterations in 0.11063949999999956s


## Vectorising Code

In [6]:
def procedural_random_walker():
    position = 0
    walk = [ position ]
    
    for i in range(1000):
        position += 2 * random.randint(0, 1) - 1
        walk.append(position)
    
    return walk

print('Finish running 100 iterations in ' + str(timeit.timeit(stmt = procedural_random_walker, number = 100)) + 's')

Finish running 100 iterations in 0.11487190000000069s


In [7]:
def faster_random_walk():
    from itertools import accumulate
    
    steps = random.choices([-1,+1], k=1000)
    return [0]+list(accumulate(steps))

print('Finish running 100 iterations in ' + str(timeit.timeit(stmt = faster_random_walk, number = 100)) + 's')

Finish running 100 iterations in 0.02212699999999934s


## Vectorising Code & Problem

Multiply elements in list A by elements in list B and sum the results.

In [8]:
def compute_python():
    A = np.arange(100)
    B = np.arange(100)
    result = 0
    for i in range(len(A)):
        for j in range(len(B)):
            result += A[i] * B[j]
    return result

print('Finish running 100 iterations in ' + str(timeit.timeit(stmt = compute_python, number = 100)) + 's')

Finish running 100 iterations in 0.42318139999999893s


In [9]:
def compute_numpy():
    A = np.arange(100)
    B = np.arange(100)
    
    Z = A.reshape(len(A),1) * B.reshape(1,len(B))
    return Z.sum()

print('Finish running 100 iterations in ' + str(timeit.timeit(stmt = compute_numpy, number = 100)) + 's')

Finish running 100 iterations in 0.004700099999999097s


In [10]:
def compute_numpy_better():
    A = np.arange(100)
    B = np.arange(100)
    return np.sum(A) * np.sum(B)

print('Finish running 100 iterations in ' + str(timeit.timeit(stmt = compute_numpy, number = 100)) + 's')

Finish running 100 iterations in 0.0037634000000004164s


## Dangers of Numpy

In [11]:
Z = np.arange(9)
print(Z)

Z_ = Z[:3]
print(Z_)

Z_ = Z[[0,1,2]]
print(Z_)

[0 1 2 3 4 5 6 7 8]
[0 1 2]
[0 1 2]


What is the difference between the two?

In [12]:
Z = np.arange(9)
Z_ = Z[:3]
Z_[...] = 100
print(Z)
print(Z_.base is Z)

[100 100 100   3   4   5   6   7   8]
True


In [13]:
Z = np.arange(9)
Z_ = Z[[0,1,2]]
Z_[...] = 100
print(Z)
print(Z_.base is Z)

[0 1 2 3 4 5 6 7 8]
False


## Reference

https://www.labri.fr/perso/nrougier/from-python-to-numpy/